Repository AY2324S1-CS2103T-F12-4/tp, pull requests merged in 2023-10, with the labels that each got.

#39 Add non-functional requirements to Developer Guide
  docs/DeveloperGuide.md
  docs/team/juzzztinsoong.md
Labels: documentation

#41 Update Glossary in Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#58 Delete meetings
  src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
  src/main/java/seedu/address/logic/commands/DeleteMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/TitleContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteMeetingCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteMeetingCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalMeetings.java
Labels: priority.High

#62 Fix attendee appearing in schedule
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/resources/view/MeetingScheduleCard.fxml
Labels: bug

#77 Update juzzztinsoong.md
  docs/team/juzzztinsoong.md
Labels: documentation

#80 Edit meeting + Additional test cases
  docs/UserGuide.md
  docs/team/lomaply.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
  src/main/java/seedu/address/logic/commands/FindMeetingCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/ViewMeetingCommandParser.java
  src/main/java/seedu/address/model/meeting/MeetingTime.java
  src/main/java/seedu/address/ui/InfoDisplayPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/InfoDisplayPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/EditMeetingDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditMeetingCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ViewMeetingCommandParserTest.java
  src/test/java/seedu/address/testutil/EditMeetingDescriptorBuilder.java
  src/test/java/seedu/address/testutil/MeetingBuilder.java
Labels: type.Story, priority.Medium

#87 DG update
  docs/DeveloperGuide.md
  docs/team/jason-raiin.md
Labels: type.Task

#97 Add DG entry for rmmc
  docs/DeveloperGuide.md
  docs/diagrams/RemoveAttendeeSequenceDiagram.puml
  docs/images/RemoveAttendeeSequenceDiagram.png
Labels: documentation, type.Task
